name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install codecov pytest-cov || pip3 install --user codecov pytest-cov;
    - name: Run tests
      run: |
        pip3 install .
        coverage run --source=rdata/ pytest;
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
